SistemaInventario/Areas/Admin/Controllers/BodegaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SistemaInventario.AccesoDatos.Repositorio.IRepositorio;
using SistemaInventario.Modelos;
using SistemaInventario.Utilidades;

namespace SistemaInventario.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BodegaController : Controller
    {
        private readonly IUnidadTrabajo _unidadTrabajo;

        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Bodega bodega = new Bodega();
            if (id == null)
            {
                // crear una nueva bodega
                bodega.Estado = true;
                return View(bodega);
            }
            //Actualizamos bodega
            bodega = await _unidadTrabajo.Bodega.Obetener(id.GetValueOrDefault());
            if (bodega == null) {
                return NotFound();
            }
            return View(bodega);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if(bodega.Id == 0)
                {
                    await _unidadTrabajo.Bodega.Agregar(bodega);
                    TempData[DS.Exito] = "Bodega Creada Exitosamente";
                }else
                {
                    _unidadTrabajo.Bodega.Actualizar(bodega);
                    TempData[DS.Exito] = "Bodega Actualizada Exitosamente";
                }

                await _unidadTrabajo.Guardar();
                return RedirectToAction("Index");
            }
            TempData[DS.Error] = "Error al grabar Exitosamente";
            return View(bodega);
        }

        #region API
        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Bodega.ObtenerTodos(null, null, null, true);
            return Json(new { data = todos });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var bodegaDB = await _unidadTrabajo.Bodega.Obetener(id);
            if (bodegaDB == null)
            {
                return Json(new {success = false, message = "error al borar la bodega"});
            }
            _unidadTrabajo.Bodega.Remover(bodegaDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega borrada correctamente" });
        }

        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            bool valor = false;
            var lista = await _unidadTrabajo.Bodega.ObtenerTodos(null, null, null, true);
            if (id == 0)
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
            }else
            {
                valor = lista.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
            }

            if (valor)
            {
                return Json(new {data = true});
            }
            return Json(new { success = false, });

        }
        #endregion
    }
}

SistemaInventario/Areas/Inventario/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaInventario.Modelos.ViewModels;
using System.Diagnostics;

namespace SistemaInventario.Areas.Inventario.Controllers
{
    [Area("Inventario")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaInventario/Areas/Admin/Views/Bodega/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-6">
        <h2 class="text-primary">Lista de bodegas</h2>
    </div>
    <div class="col-lg-6">
        <a class="btn btn-outline-primary" asp-action="Upsert"> <i class="bi bi-plus-square-fill"></i> Crear Nueva Bodega</a>
    </div>
    <br/>
    <div class="p-4 border reounded bg-ligth">
        <table id="tblDatos" class="table table-responsive table-hover">
            <thead class="table-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/Bodega.js"></script>
}

SistemaInventario/Areas/Admin/Views/Bodega/Upsert.cshtml
@model SistemaInventario.Modelos.Bodega
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var titulo = "Crear Bodega";
}

<form method="post">
    <div style="padding-left:15%; padding-right:15%; padding-bottom:inherit.4rem;">
        <div class="rounded-end border-0">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if(Model.Id != 0)
            {
                //Actualizar
                titulo = "Actualizar Bodega";
                <input type="hidden" asp-for="Id" id="id"/>
            }
            <div class="col-12 border-bottom p-0">
                <h2 class="text-primary">@titulo</h2>
            </div>

            <div class="row mb-2 mt-2">
                <div class="form-group col-md-6">
                    <label>Nombre</label>
                    <input type="text" asp-for="Nombre" class="form-control" placeholder="Nombre de la Bodega" id="nombre"/>
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-2 mt-2">
                <div class="form-group col-md-6">
                    <label>Descripcion</label>
                    <input type="text" asp-for="Descripcion" class="form-control" placeholder="Descripcion de la Bodega" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>
            <div class="row mb-2 mt-2">
                <div class="form-group col-md-6">
                    <label>Estado</label>
                    <select asp-for="Estado" class="form-select">
                        <option value=true>Activo</option>
                        <option value=false>Inactivo</option>
                    </select>
                    <span asp-validation-for="Estado" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br/>
        @if(Model.Id != 0)
        {
            <partial name="_BotonesActualizarRegresar" model="Model.Id"/>
        }else
        {
            <partial name="_BotonesCrearRegresar" model="Model.Id" />
        }
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    <script>
        document.getElementById("nombre").addEventListener('change', function(){
            validarNombre();
        });

        function validarNombre(){
            var url = '@Url.Content("~/")'+ "Admin/Bodega/ValidarNombre";
            var id = '#id';
            var nombre = '#nombre';

            $.getJSON(url, {id: $(id).val(), nombre: $(nombre).val()}, function (data) {
                $.each(data, function (key, value) {
                    if(value) {
                            var nombre = document.getElementById("nombre");
                            swal("Error", "nombre ya existe", "error");
                            nombre.value = ""
                    }
                })
            });
        }
    </script>
}

SistemaInventario/Areas/Inventario/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Inventary</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SistemaInventario/Views/Shared/_BotonesActualizarRegresar.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false" asp-route-id="@Model"> <i class="bi bi-pencil-square"></i> Guardar Cambios</button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i>Regresar</a>
</div>

SistemaInventario/Views/Shared/_BotonesCrearRegresar.cshtml
<div class="d-grid gap-2 d-md-block">
    <button type="submit" class="btn btn-primary" onfocus="false"> <i class="bi bi-plus-square-fill"></i> Crear</button>
    <a asp-action="Index" class="btn btn-success"> <i class="bi bi-arrow-return-left"></i>Regresar</a>
</div>

SistemaInventario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaInventario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaInventario.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaInventario</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#"  data-bs-toggle="dropdown" aria-expanded="false">Contenido</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="Admin" asp-controller="Bodega" asp-action="Index">Bodegas</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notificaciones" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaInventario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaInventario/Views/Shared/_Notificaciones.cshtml
@using SistemaInventario.Utilidades

@if (TempData[DS.Exito] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Exito]');
    </script>
}

@if (TempData[DS.Error] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Error]');
    </script>
}